version: "3"
services:
  webappointments-app:
    build:
      context: Dockerfile.dev
    ports:
      - "8099:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_MEDERE_ADDRESS=http://medere1.medere.localhost:8080
      - CHOKIDAR_USEPOLLING=true